language: generic

sudo: false

matrix:
  include:
    # TODO Add Python2.7 testing once compatibility issues are fixed.
    #- { os: linux, env: PYTHON_VERSION=2.7 }
    - { os: linux, env: PYTHON_VERSION=3.4 }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    # Mac OS-X testing disabled since conda/glotzer/hoomd does not run
    # on any of the Travis CI images.
    #- { os: osx, env: PYTHON_VERSION=3.5 }

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_conda.sh
  - conda config --add channels glotzer
  - conda config --add channels conda-forge
  - conda create -y -n travis_env python=$PYTHON_VERSION signac signac-flow hoomd gsd jupyter matplotlib
  - source activate travis_env

script:
  - python -m my_project.init 0
  - python -m my_project.status -d
  - python -m my_project.submit --test --ppn 1
  - python scripts/run.py auto
  - python -m my_project.status -d
  - python -m jupyter nbconvert --to html --execute analysis/notebook.ipynb
